add more facebook groups and a volunteering opportunity
acqcolor/bayareawomenintech pull request #5
Opened 2016-10-01 05:29 UTC by polinadotio

#hacktoberfest 👻 🎃 🍺

2016-10-01 20:22 UTC, acqcolor commented on README.md
> +* [Silicon Valley Women](https://www.facebook.com/groups/SVWomen/)
Would you mind adding a line or two describing the purpose of the group?

2016-10-01 20:24 UTC, maggiewhite requested changes

2016-10-01 20:24 UTC, acqcolor commented on README.md
> +* [Girls in Tech - San Francisco](https://www.facebook.com/groups/55771429119/)
Same, please add a short description of the group

2016-10-02 22:32 UTC, polinadotio commented
@acqcolor sounds good! I just added descriptions for all of the groups, lmk if those work.

2016-10-02 23:22 UTC, maggiewhite approved these changes
Looks great! Thanks for the addition.

2016-10-02 23:23 UTC, merged